### ISSUE TITLE
ValueError when running

### ISSUE THREAD

**Issue by master117** [aziascreations/Youtube-Auto-Archiver#1]
Hi, hit this error today when trying out using Python3.11

```python

Traceback (most recent call last):
  File "Y:\v&uarchiver\Youtube-Auto-Archiver-main\app.py", line 10, in <module>
    import yaa.config as yaa_config
  File "Y:\v&uarchiver\Youtube-Auto-Archiver-main\yaa\config.py", line 170, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'yaa.config.ConfigApplication'> for field application is not allowed: use default_factory
```

**Comment by aziascreations** [comment]
Hi, thanks for reporting the issue.
It seems this issue is comming from a breaking change in Python 3.11 regarding the default values for mutables.
I'll look into it since the bottom of this section of their doc appears to mention something that's used in the config classes.  (See: [Python 3.11 - Dataclasses - Mutable Default Values](https://docs.python.org/3/library/dataclasses.html#mutable-default-values))

Edit: Just in case, you can still use Python 3.10 in the meantime if you really need to use the application.

**Comment by aziascreations** [comment]
The issue has been fixed.
I'm sorry this took so long, a complete refactoring was planned and the whole thing fell apart due to scope creep and ack of interest...
